# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master
- development

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '3.0.x'
    
- script: dotnet build --configuration $(buildConfiguration)
  displayName: '.NET Build'

- task: Docker@2
  displayName: 'Build Docker Image and Push to Docker Hub (Master)'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  inputs:
    containerRegistry: 'Docker Hub - Faction'
    repository: 'faction/build-dotnet'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 'latest'

- task: Docker@2
  displayName: 'Build Docker Image and Push to Docker Hub (Development)'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/development'))
  inputs:
    containerRegistry: 'Docker Hub - Faction'
    repository: 'faction/build-dotnet'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 'dev'
